### ISSUE TITLE
Missing expert in Android: Shelly Gill

### ISSUE THREAD

**Issue by eric906** [esri-es/arcgis-experts#11]
If you are suggesting a new expert please fill this template:

Shelly Gill

![image](https://user-images.githubusercontent.com/3476407/34693490-973f1fea-f478-11e7-82b9-8ae9a48ea04b.png)
```


{
    "name": Shelly Gill,
    "picture": null,
    "linkedin": null,
    "twitter": null,
    "github": shellygill,
    "geonet": sgill-esristaff,
    "arcgis": null,
    "stackoverflow": null,
    "stackexchange": null,
    "geodev": false,
    "advocate": true,
    "technologies": null
}

```
cc @hhkaos

**Comment by hhkaos** [comment]
[Done](https://esri-es.github.io/arcgis-experts/#expert=shelly-gill) @eric906 ! thx!!
