### ISSUE TITLE
Missing expert in Android: Jeff Ford

### ISSUE THREAD

**Issue by eric906** [esri-es/arcgis-experts#12]
If you are suggesting a new expert please fill this template:

Jeff Ford

![image](https://user-images.githubusercontent.com/3476407/34694222-2575b61e-f47b-11e7-8b8c-ae3c6016aca3.png)

```
{
    "name": Jeff Ford,
    "picture": null,
    "linkedin": null,
    "twitter": null,
    "github": null,
    "geonet": null,
    "arcgis": null,
    "stackoverflow": null,
    "stackexchange": null,
    "geodev": false,
    "advocate": false,
    "technologies": Android
}
```

**Comment by hhkaos** [comment]
[Done](https://esri-es.github.io/arcgis-experts/#expert=jeff-ford)!! Thx @eric906 !
