### ISSUE TITLE
Update Speciality 

### ISSUE THREAD

**Issue by astauffer** [esri-es/arcgis-experts#25]
Great idea to help people find the right resources around Esri! I no longer work on the Open Data, Hub, or ArcGIS Online product teams, so will have to request that those are removed for me. I have however transitioned into a role where I work with Waze, Teralytics, and a few other companies.

**Comment by hhkaos** [comment]
Thanks @astauffer!, I didn't know you transitioned to a different team! I just updated [your profile](https://esri-es.github.io/arcgis-experts/#expert=andrew-stauffer). 

Cheers!
