### ISSUE TITLE
Franz Pucha Cofrep

### ISSUE THREAD

**Issue by franzpc** [esri-es/arcgis-experts#31]
If you are suggesting a new expert please fill this template:

```
{
    "consent": true,
    "name": "Franz Pucha Cofrep",
    "picture": "https://franzpc.files.wordpress.com/2018/03/img_20170912_145911_430.jpg",
    "linkedin": "https://www.linkedin.com/in/franzpc/",
    "twitter": "https://twitter.com/franzpc/",
    "github": "https://github.com/franzpc",
    "geonet": null,
    "arcgisonline": null,
    "stackoverflow": null,
    "stackexchange": null,
    "youtube": "http://www.youtube.com/franzpc",
    "blog": "https://geogeek.xyz",
    "website": "https://acolita.com",
    "podcast": null,
    "geodev": false,
    "advocate": false,
    "technologies": "GIS, Remote Sensing, Python, ArcGIS Pro, Story Maps, ArcGIS Online"
}
```

**Comment by hhkaos** [comment]
Thanks @franzpc !

I have just added new information to the [contribution guide](https://github.com/esri-es/arcgis-experts/blob/master/CONTRIBUTING.md#expert-profile) and added an update to the [issue template](https://github.com/esri-es/arcgis-experts/blob/master/ISSUE_TEMPLATE.md) so you can check the JSON syntax.

Please check it out and update the issue.

Thanks in advance
