### ISSUE TITLE
Adrián Pérez

### ISSUE THREAD

**Issue by AdriSolid** [esri-es/arcgis-experts#32]
If you are suggesting a new expert please fill this template:

```
{
    "consent": true,
    "name": "Adrián Pérez",
    "picture": "https://media.licdn.com/dms/image/C4E03AQGksnr9owmBTg/profile-displayphoto-shrink_200_200/0?e=1526680800&v=alpha&t=pPx0SiusNN06ggqvsfDl4nYYGOzHf6Y92__z9XgOeLA",
    "linkedin": "https://www.linkedin.com/in/adri%C3%A1n-p%C3%A9rez-beneito-414771a6/",
    "twitter": null,
    "github": "https://github.com/AdriSolid",
    "geonet": "https://community.esri.com/people/Adri2c",
    "arcgisonline": "http://adri2c.maps.arcgis.com/home/index.html",
    "stackoverflow": null,
    "stackexchange": null,
    "youtube": null,
    "blog": null,
    "website": null,
    "podcast": null,
    "geodev": true,
    "advocate": true,
    "technologies": "ArcGIS API for JavaScript 3.x, ArcGIS API for JavaScript 4.x, ArcGIS REST API, ArcPy, Cedar, Dojo, Esri Leaflet, Web AppBuilder for ArcGIS - Developer Edition, Widgets"
}
```

**Comment by hhkaos** [comment]
Thanks @AdriSolid !!

I have just added new information to the [contribution guide](https://github.com/esri-es/arcgis-experts/blob/master/CONTRIBUTING.md#expert-profile) and added an update to the [issue template](https://github.com/esri-es/arcgis-experts/blob/master/ISSUE_TEMPLATE.md) so you can check the JSON syntax.

Please check it out and update the issue.

Thanks in advance!

**Comment by AdriSolid** [comment]
Thanks @hhkaos 

'En casa del herrero, cuchillo de palo'

Cheers

**Comment by hhkaos** [comment]
>     "advocate": false,

Oooohh, you are not willing to help others on GeoNet? :sob:

**Comment by AdriSolid** [comment]
Well, I was thinking about it. I help in the forum, but I'm not one of the most active people there, I think.. I'm going to edit it. 

Cheers!

**Comment by hhkaos** [comment]
Done!
