### ISSUE TITLE
Ben Flanagan

### ISSUE THREAD

**Issue by bflanaganesri** [esri-es/arcgis-experts#33]
{
    "consent": true,
    "name": "Ben Flanagan",
    "picture": "https://pbs.twimg.com/profile_images/1001762356492492800/5NPLaf12_400x400.jpg",
    "linkedin": "https://www.linkedin.com/in/flanaganben/",
    "twitter": "https://twitter.com/benflan",
    "github": null,
    "geonet": "https://community.esri.com/people/BFlanaganesriuk-esridist",
    "arcgisonline": null,
    "stackoverflow": null,
    "stackexchange": null,
    "youtube": null,
    "blog": null,
    "website": null,
    "podcast": null,
    "geodev": false,
    "advocate": true,
    "technologies": "Vector Tiles, ArcGIS Online, Story Maps, ArcGIS Pro, Cartography, UX, User Experience, Web Map, Web App Builder, Design, ArcGIS Desktop, Web Apps, Spatial Analysis"
}

**Comment by hhkaos** [comment]
Thx @bflanaganesri ! done! :smile:
